export const DEFAULT_WALKING_SPEED_METERS_PER_SECOND = 1.2;

export const DEFAULT_MAX_WALKING_DISTANCE_METERS = 500;

export const DEFAULT_MAX_DEBUG_CONNECTIONS = 50;

export const WALK_GEOMETRY_MAPTILER_MIN_DISTANCE_METERS = 100;

export const MAPTILER_DIRECTIONS_TIMEOUT_MS = 5_000;
