process.env.NODE_ENV = 'test';
process.env.PORT = '3000';
process.env.APP_NAME = 'Transit Backend';
process.env.API_KEY = 'test-api-key-minimum-length-24chars';
process.env.INTERNAL_SERVICE_TOKEN = 'test-internal-token-min-length-24';
process.env.ENABLE_INTERNAL_ENDPOINTS = 'false';
process.env.CORS_ORIGIN = 'http://localhost:3000';
process.env.SWAGGER_ENABLED = 'false';
process.env.JWT_ACCESS_SECRET = 'test-jwt-access-secret-minimum-32-chars!!';
process.env.JWT_ACCESS_EXPIRES_IN = '15m';
process.env.JWT_REFRESH_SECRET = 'test-jwt-refresh-secret-minimum-32-chars!';
process.env.JWT_REFRESH_EXPIRES_IN = '90d';
process.env.DATABASE_URL =
  'postgresql://transit:transit@localhost:5432/transit_db?schema=public';
