services:
  api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:8.6-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-transit}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-transit}
      POSTGRES_DB: ${POSTGRES_DB:-transit_db}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
